# Generated by Django 3.1.1 on 2021-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_details_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
