# Generated by Django 3.0.6 on 2021-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20210327_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='care_growing',
            field=models.TextField(default='empty', null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='care_growing1_show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='diseases_show',
            field=models.BooleanField(default=False),
        ),
    ]
