# Generated by Django 3.0.6 on 2021-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20210327_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='fartilizer',
            field=models.TextField(default='empty', null=True),
        ),
        migrations.AddField(
            model_name='product_details',
            name='fartilizer_show',
            field=models.BooleanField(default=False),
        ),
    ]
